import { planSchema, type Plan } from "./domain";
export function leadershipDemo(): Plan {
  const people = [
    [
      "uxd-head",
      "Avery Morgan",
      "design",
      null,
      "Head of Design",
      "UXD",
      true,
      0,
      100,
    ],
    [
      "elena",
      "Elena Brooks",
      "design",
      "uxd-head",
      "VP of Design, Digital Products",
      "Product Design",
      true,
      0.4,
      50,
    ],
    [
      "marcus",
      "Marcus Reed",
      "research",
      "uxd-head",
      "VP of Design, Research",
      "Design Research",
      true,
      0.4,
      50,
    ],
    [
      "priya",
      "Priya Shah",
      "content",
      "uxd-head",
      "VP of Design, Content & Conversation",
      "Content & Conversation Design",
      true,
      0.4,
      50,
    ],
    [
      "daniel",
      "Daniel Kim",
      "design_eng",
      "uxd-head",
      "VP of Design, Systems & Engineering",
      "Design Systems & Engineering",
      true,
      0.4,
      50,
    ],
    [
      "maya",
      "Maya Chen",
      "design",
      "elena",
      "Product Design Manager",
      "Product Design",
      true,
      1,
      20,
    ],
    [
      "jordan",
      "Jordan Ellis",
      "design",
      "elena",
      "Staff Product Designer",
      "Product Design",
      false,
      1,
      20,
    ],
    [
      "nina",
      "Nina Patel",
      "design",
      "maya",
      "Product Designer",
      "Product Design",
      false,
      1,
      15,
    ],
    [
      "sofia",
      "Sofia Ramirez",
      "research",
      "marcus",
      "Staff Design Researcher",
      "Design Research",
      false,
      1,
      20,
    ],
    [
      "ethan",
      "Ethan Park",
      "research",
      "marcus",
      "Senior Design Researcher, Research Platforms",
      "Design Research",
      false,
      0.8,
      20,
    ],
    [
      "amara",
      "Amara Nwosu",
      "research",
      "marcus",
      "Design Researcher, AI Experiences",
      "Design Research",
      false,
      1,
      25,
    ],
    [
      "leo",
      "Leo Martinez",
      "content",
      "priya",
      "Staff Content Designer",
      "Content & Conversation Design",
      false,
      1,
      20,
    ],
    [
      "grace",
      "Grace Liu",
      "content",
      "priya",
      "Senior Content Designer, Design Systems",
      "Content & Conversation Design",
      false,
      1,
      20,
    ],
    [
      "theo",
      "Theo Reed",
      "content",
      "priya",
      "Conversation Designer",
      "Content & Conversation Design",
      false,
      0.8,
      20,
    ],
    [
      "oliver",
      "Oliver Grant",
      "design_eng",
      "daniel",
      "Staff Design Engineer",
      "Design Systems & Engineering",
      false,
      1,
      20,
    ],
    [
      "isabel",
      "Isabel Costa",
      "design_eng",
      "daniel",
      "Design Engineer, Accessibility",
      "Design Systems & Engineering",
      false,
      1,
      20,
    ],
    [
      "noah",
      "Noah Bennett",
      "design_eng",
      "daniel",
      "Design Engineer, Prototyping",
      "Design Systems & Engineering",
      false,
      1,
      15,
    ],
    [
      "sana",
      "Sana Ahmed",
      "design",
      "uxd-head",
      "VP of Design, Experience Strategy",
      "Experience Strategy",
      true,
      0.4,
      50,
    ],
    [
      "victor",
      "Victor Alvarez",
      "design",
      "uxd-head",
      "VP of Design, Emerging Experiences",
      "Emerging Experiences",
      true,
      0.4,
      50,
    ],
    [
      "riley",
      "Riley Thompson",
      "design_eng",
      "uxd-head",
      "VP of Design, AI Products",
      "AI Product Design",
      true,
      0.4,
      50,
    ],
    [
      "tessa",
      "Tessa Wu",
      "design",
      "sana",
      "Principal Experience Strategist",
      "Experience Strategy",
      false,
      1,
      20,
    ],
    [
      "owen",
      "Owen Hughes",
      "design",
      "sana",
      "Senior Service Designer",
      "Experience Strategy",
      false,
      1,
      20,
    ],
    [
      "leila",
      "Leila Haddad",
      "design",
      "victor",
      "Staff Product Designer, Emerging Experiences",
      "Emerging Experiences",
      false,
      1,
      20,
    ],
    [
      "ben",
      "Ben Carter",
      "design_eng",
      "victor",
      "Design Engineer, Creative Technology",
      "Emerging Experiences",
      false,
      1,
      20,
    ],
    [
      "aisha",
      "Aisha Patel",
      "design",
      "riley",
      "Staff Product Designer, AI Experiences",
      "AI Product Design",
      false,
      1,
      20,
    ],
    [
      "sam",
      "Sam Okafor",
      "design_eng",
      "riley",
      "Design Engineer, AI Prototyping",
      "AI Product Design",
      false,
      1,
      20,
    ],
  ].map(
    ([
      id,
      name,
      craft,
      managerId,
      title,
      team,
      isLeader,
      fte,
      nonProjectPct,
    ]) => ({
      id,
      name,
      craft,
      managerId,
      title,
      team,
      isLeader,
      fte,
      nonProjectPct,
    }),
  );
  const projects = [
    {
      id: "opening",
      name: "Account opening redesign",
      priority: "Client onboarding",
      leadId: "maya",
      memberIds: ["sofia", "leo", "oliver"],
      importance: "top",
      health: "needs_decision",
      delivery: "in_progress",
      summary:
        "Help new clients open an account without getting stuck or starting over.",
      update:
        "The shorter application has been tested. The team is ready to finalize the identity-check experience.",
      decision:
        "Decide whether the new identity check belongs in this release or the next one.",
      start: "2026-10-01",
      end: "2026-11-20",
      effort: { design: 1, research: 0.5, content: 0.4, design_eng: 0.5 },
      dependsOn: ["components"],
    },
    {
      id: "advisor",
      name: "Advisor workspace",
      priority: "Advisor productivity",
      leadId: "jordan",
      memberIds: ["sofia", "grace"],
      importance: "top",
      health: "on_track",
      delivery: "in_progress",
      summary:
        "Bring the right client information into one place before every advisor meeting.",
      update:
        "Advisors have reviewed the new workspace. The team is refining the meeting-preparation flow.",
      start: "2026-10-01",
      end: "2026-12-04",
      effort: { design: 0.8, research: 0.4, content: 0.3, design_eng: 0.3 },
    },
    {
      id: "retirement",
      name: "Retirement guidance",
      priority: "Client financial planning",
      leadId: "leo",
      memberIds: ["ethan", "maya"],
      importance: "top",
      health: "at_risk",
      delivery: "in_progress",
      summary:
        "Make retirement choices easier to understand, so clients know what to do next.",
      update:
        "Participant recruitment is slower than expected. The research lead is adjusting the interview plan.",
      start: "2026-10-12",
      end: "2026-12-11",
      effort: { design: 0.3, research: 0.5, content: 0.6, design_eng: 0.1 },
    },
    {
      id: "components",
      name: "Accessible component library",
      priority: "Shared experience capabilities",
      leadId: "oliver",
      memberIds: ["isabel", "grace"],
      importance: "high",
      health: "on_track",
      delivery: "in_progress",
      summary:
        "Give every team accessible, reusable components for the journeys clients use most.",
      update:
        "Forms and navigation are ready for adoption. Account opening and mobile teams are coordinating the rollout.",
      start: "2026-10-01",
      end: "2026-12-18",
      effort: { design: 0.3, research: 0.1, content: 0.2, design_eng: 1 },
    },
    {
      id: "insights",
      name: "Research repository",
      priority: "Shared experience capabilities",
      leadId: "ethan",
      memberIds: ["amara", "jordan"],
      importance: "high",
      health: "on_track",
      delivery: "in_progress",
      summary:
        "Make existing client research easy to find before teams start new work.",
      update:
        "The first set of findings is organized around client journeys. Two teams are trying the search experience.",
      start: "2026-10-05",
      end: "2026-11-27",
      effort: { design: 0.2, research: 0.5, content: 0.1, design_eng: 0.2 },
    },
    {
      id: "mobile",
      name: "Mobile portfolio overview",
      priority: "Client financial planning",
      leadId: "nina",
      memberIds: ["noah", "leo"],
      importance: "high",
      health: "at_risk",
      delivery: "in_progress",
      summary:
        "Help clients understand portfolio performance at a glance on their phone.",
      update:
        "The design is progressing, but delivery depends on shared chart and accessibility components.",
      start: "2026-10-19",
      end: "2026-12-18",
      effort: { design: 0.7, research: 0.2, content: 0.2, design_eng: 0.6 },
      dependsOn: ["components"],
    },
    {
      id: "statements",
      name: "Statement content redesign",
      priority: "Client financial planning",
      leadId: "grace",
      memberIds: ["theo", "maya"],
      importance: "normal",
      health: "on_track",
      delivery: "completed",
      summary:
        "Replace confusing statement terminology with language clients can understand.",
      update: "The reviewed copy has been handed over to the statements team.",
      start: "2026-10-01",
      end: "2026-10-09",
      effort: { design: 0.1, research: 0, content: 0.5, design_eng: 0 },
    },
    {
      id: "coaching",
      name: "Planning assistant discovery",
      priority: "Client financial planning",
      leadId: "amara",
      memberIds: ["nina", "isabel"],
      importance: "normal",
      health: "not_reported",
      delivery: "planned",
      status: "proposed",
      summary:
        "Explore whether guided prompts can help clients take their next planning step.",
      update:
        "An early idea for next quarter. The team has not committed to delivery.",
      start: "2026-11-16",
      end: "2026-12-31",
      effort: { design: 0.4, research: 0.4, content: 0.2, design_eng: 0.3 },
    },
    {
      id: "experience-strategy",
      name: "UXD product design strategy",
      priority: "Product experience alignment",
      leadId: "tessa",
      memberIds: ["owen", "maya", "sofia"],
      importance: "top",
      health: "on_track",
      delivery: "in_progress",
      summary:
        "Define shared experience principles and a prioritized roadmap across onboarding, advice, and retirement products.",
      update:
        "Journey reviews are complete. Product Design and Research are validating the proposed investment priorities.",
      start: "2026-10-01",
      end: "2026-11-06",
      effort: { design: 0.5, research: 0.2, content: 0.1, design_eng: 0 },
    },
    {
      id: "innovation-lab",
      name: "Service concept pilots",
      priority: "New product opportunities",
      leadId: "leila",
      memberIds: ["ben", "owen", "nina"],
      importance: "high",
      health: "on_track",
      delivery: "in_progress",
      summary:
        "Test two service concepts with clients before committing to product development.",
      update:
        "Prototype scenarios are ready. Design Strategy is defining the success criteria with Product Design.",
      start: "2026-10-12",
      end: "2026-12-11",
      effort: { design: 0.5, research: 0.2, content: 0.1, design_eng: 0.4 },
      dependsOn: ["experience-strategy"],
    },
    {
      id: "conversational-prototype",
      name: "Conversational planning prototype",
      priority: "New product opportunities",
      leadId: "ben",
      memberIds: ["aisha", "amara", "leo"],
      importance: "high",
      health: "needs_decision",
      delivery: "in_progress",
      summary:
        "Evaluate a conversational planning concept with clear handoffs to human support.",
      update:
        "Two interaction approaches have been tested with internal reviewers. Client testing is awaiting a scope decision.",
      decision:
        "Select one concept and approve the client-testing scope for the next pilot.",
      start: "2026-10-26",
      end: "2026-12-18",
      effort: { design: 0.3, research: 0.2, content: 0.2, design_eng: 0.6 },
      dependsOn: ["ai-standards"],
    },
    {
      id: "ai-standards",
      name: "UX AI interaction standards",
      priority: "Responsible AI experiences",
      leadId: "aisha",
      memberIds: ["sam", "grace", "oliver"],
      importance: "top",
      health: "on_track",
      delivery: "in_progress",
      summary:
        "Define reusable interaction patterns for AI disclosures, source references, user feedback, and error recovery.",
      update:
        "Content Design has reviewed the patterns. Design Systems is preparing the first component examples.",
      start: "2026-10-05",
      end: "2026-11-13",
      effort: { design: 0.4, research: 0.1, content: 0.3, design_eng: 0.4 },
      dependsOn: ["components"],
    },
    {
      id: "ai-research",
      name: "AI-assisted research synthesis",
      priority: "Shared experience capabilities",
      leadId: "sam",
      memberIds: ["ethan", "amara", "tessa"],
      importance: "high",
      health: "at_risk",
      delivery: "in_progress",
      summary:
        "Pilot AI-assisted research summaries with source citations and researcher review before publication.",
      update:
        "The evaluation tool is ready, but preparation of the de-identified research dataset is behind schedule.",
      decision:
        "Confirm researcher availability for dataset review before the pilot starts.",
      start: "2026-11-02",
      end: "2026-12-18",
      effort: { design: 0.2, research: 0.4, content: 0.1, design_eng: 0.7 },
      dependsOn: ["insights", "ai-standards"],
    },
  ];
  return planSchema.parse({
    revision: 0,
    people,
    initiatives: projects.map((p) => ({
      status: "committed",
      ...p,
      owner: people.find((x) => x.id === p.leadId)?.name || "",
    })),
  });
}
export function isStarterPlan(plan: Plan) {
  return (
    plan.people.length === 12 &&
    plan.initiatives.length === 5 &&
    plan.initiatives.every(
      (i) =>
        [
          "Unified workspace",
          "Onboarding refresh",
          "Enterprise discovery",
          "Accessible foundations",
          "Self-service analytics",
        ].includes(i.name) &&
        !i.priority &&
        !i.owner &&
        !i.summary &&
        i.delivery === "planned" &&
        !i.leadId,
    ) &&
    !plan.people.some((p) => p.managerId)
  );
}
